### ISSUE TITLE
support for contentment datatypes

### ISSUE THREAD

**Issue by ribsdigital** [outfielddigital/konstrukt#12]
hi matt,

we've hit an issue where a [contentment](https://github.com/leekelleher/umbraco-contentment) datatype isn't loading when set as a field datatype...

the datatype we've been exprimenting with is a datalist reading from an enum and rendering as a radio button list:

![image](https://user-images.githubusercontent.com/22835873/163075908-0d0c0c85-00ef-4fe9-8120-acd07ee5ce27.png)

there are no errors raised in the logs and/or the backoffice, the datatype just doesn't appear to load:

![image](https://user-images.githubusercontent.com/22835873/163076118-3b3c7e28-1544-48c3-9e76-15c8bca72e2f.png)

appreicate [contentment](https://github.com/leekelleher/umbraco-contentment) is a 3rd party plugin so it may not be supported but we wanted to run it by you 👍

**Comment by mattbrailsford** [comment]
@ribsdigital I'll see if I can see why it doesn't work, but just a heads up, when reporting issues you need to report them on the `konstrukt` repo. You seem to keep raising them on the `konstrukt-documentation` repo which is intended for documentation issues. I've transferred this issue over to the correct repo, but just thought I'd mention it for future issues.

**Comment by mattbrailsford** [comment]
@ribsdigital ok, there should be a 1.0.3-beta0002 on the unstable feed shortly which resolves this. If you wanna give it a try and let me know if it works for you 👍

**Comment by ribsdigital** [comment]
hi @mattbrailsford appologies for posting on the wrong repo... i'll post any further issues here 👍 

we've just tried out the beta version and although it fixes the issue with the contentment datatype, all datatypes that're based on content pickers are now failing!

editing an exisiting entity results in the picked content failing to load.

creating a new entity allows picking, but once a piece of content is selected the following console error occurs:

![image](https://user-images.githubusercontent.com/22835873/163920956-6ff4668a-8518-4853-a455-f3f8efad3316.png)
![image](https://user-images.githubusercontent.com/22835873/163920983-13d9407a-7d70-4274-a188-f0cf41c0d36f.png)

if we revert back to v1.0.2 everything the content pickers work as expected...

weird! does this happen on your side?

**Comment by mattbrailsford** [comment]
I think you might be suffering from this issue https://github.com/umbraco/Umbraco-CMS/issues/10951 (that unfortunately got closed) but it seems you have a mix of ID types being posted back to the content API which it doesn’t like. 

I’ll have to take give it a try on my local install

**Comment by mattbrailsford** [comment]
@ribsdigital are you using the normal content picker? or do you have a custom picker implementation anywhere?

**Comment by ribsdigital** [comment]
hi @mattbrailsford it's the content picker that ships with the umbraco core...

![image](https://user-images.githubusercontent.com/22835873/164126749-19bd69a2-dff1-43da-ae84-92e899e1e8dc.png)

we've tried this in a couple of projects now with the same outcome...

**Comment by mattbrailsford** [comment]
Do you have any other custom content picker implementations where in your solution? (within Konstrukt or not)

**Comment by ribsdigital** [comment]
hi @mattbrailsford no - this is running in a very skinny standalone install of umbraco that i'm using specifically for testing konstrukt. other than creating the home doctype and setting up the pocos as outined in the docos, it's not got anything else in it.

**Comment by mattbrailsford** [comment]
Hmm, then I can't think what is affecting this. It's not particularly Konstrukts issue, it's a problem in the content picker where in it's prevalue it can be told what type of id to store (int or udi) but the bug I link to is that for some reason any content picker that runs first dictates what id type must be used for ALL  content pickers across the solution.

From the error you are showing, it does look like the content picker is mixing it's id types (you've got an int id and a udi id trying to be looked up, which is what is causing the error).

As I say though, unfortunately this isn't Konstrukts issue. It's the core one I linked to.

**Comment by mattbrailsford** [comment]
I did wonder if it was something in contentment which does indeed have a treepicker in it, but it's idType is set to "udi" which I believer is the default so should be ok. It really looks like somewhere there is a picker configured with an idType of "int" and it's messing with the rest of them.

**Comment by mattbrailsford** [comment]
I'm gonna close this issue as I'm pretty sure the remaining item is a core issue and the fix for the original bug is in place. This will actually be in the upcoming 1.1.0 release
