### ISSUE TITLE
.MakeRequired() no longer mandates values when creating

### ISSUE THREAD

**Issue by matt-tolliday-iss** [outfielddigital/konstrukt#18]
**Describe the bug**
Updated to both 1.1.0 and the nightly on 1.1.1-beta0060 and using either:

`.AddField(p => p.Email, cfg => cfg.MakeRequired())`

or 

`.AddField(p => p.Email).MakeRequired()`

results in validation not firing, nor the expected red asterisk on the property/field.

**Steps To Reproduce**
1. Configure entity with field under fieldset with either .MakeRequired() on the field config extension method, or as method
2. Click create on entity in backoffice UI
3. Exception thrown as attempts to save entity with missing required field

**Expected behavior**
red asterisk marking mandatory field, and validation fired on save attempt.

**Screenshots**
![image](https://user-images.githubusercontent.com/80101704/169048119-2785d3e0-cf8f-4be4-88b1-cbbe3cd6f9ca.png)

**Environment (please complete the following information):**

- Server OS: Win10
- Browser Chrome
- Umbraco Version 9.5.0 (Also 9.4)
- Product Version 1.1.0 / 1.1.1-beta0060

**Comment by mattbrailsford** [comment]
@matt-tolliday-iss I've just had a look and I can add the client side validation no problem, but before I do this, it should by default validate at the server side and show the required validation error.

![image](https://user-images.githubusercontent.com/527305/169054178-2ccc644b-3098-48b7-905f-17d7aaf73d05.png)

Which of your fields in the screenshot are failing and causing a SQL exception? As if fields are marked as required, it should at the very least validate this at the server side.

**Comment by matt-tolliday-iss** [comment]
Okay, narrowed this down to the edge case where a property is defined as the "Name" property, and is also defined as a field in the Editor. When that field is **not provided** on Create (even if the "Name" value in the top entity bar is provided) then the following exception is thrown:

`.SetNameProperty(p => p.Email)`

`.AddField(p => p.Email, cfg => cfg.MakeRequired())`

`System.NullReferenceException: 'Object reference not set to an instance of an object.'`

`This exception was originally thrown at this call stack:
    Konstrukt.Web.Models.Mappers.KonstruktEntityMapper.ToEditModel(Konstrukt.Configuration.IKonstruktCollectionSourceConfig, Konstrukt.Configuration.KonstruktCollectionConfig, object)
    Konstrukt.Web.Controllers.Api.KonstruktApiController.SaveEntity(Konstrukt.Web.Models.KonstruktEntityPostModel)
    Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(Microsoft.AspNetCore.Mvc.Infrastructure.IActionResultTypeMapper, Microsoft.Extensions.Internal.ObjectMethodExecutor, object, object[])
    Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync.__Logged|12_1(Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
`

**Comment by mattbrailsford** [comment]
I'll look to move the duplicate property issue to it's own ticket and I'll mark this issue as closed as we now have client side vlidation enabled for required / regex validation which is really what the original question was about. This will be available for testing on the unstable feed shortly (v1.1.1-betaXXXX)

**Comment by mattbrailsford** [comment]
v1.1.1 has now been released
