### ISSUE TITLE
DataView that returns no entities errors

### ISSUE THREAD

**Issue by matt-tolliday-iss** [outfielddigital/konstrukt#27]
**Describe the bug**

When adding a DataView (this is tested as a DataView within a category, if relevant) and when that view returns no results, then the FindEntities API call returns a 500 with the following:

The url `/umbraco/backoffice/konstrukt/konstruktapi/FindEntities` returns:

`{"ExceptionMessage":"Value cannot be null. (Parameter 'source')","ExceptionType":null,"StackTrace":null}`

This is configured with:

`var today = DateTime.Today;`
`var nextMonth = DateTime.UtcNow.AddMonths(1);`
`.AddDataView("Renewal Due", "This Month", p => p.NextDueDate > today && p.NextDueDate <= nextMonth)`

(Nb: the reason for the definitions of the dates being outside the Konstrukt config is that it completely error'ed when dates were supplied inline to the query - assume NPoco limitations in query conversions)

![image](https://user-images.githubusercontent.com/80101704/170717602-02490f36-97e2-4061-9e0d-b9ecb5c4e2fb.png)

**Steps To Reproduce**
1. Configure List View with DataView that would trigger no results to be returned
2. Click on dataview after loading the list view for the collection
3. no results are returned via api

**Expected behavior**
page loads with the standard "no results" backing text.

**Environment (please complete the following information):**
Server OS: Win10
Browser Chrome
Umbraco Version 9.5.0 (Also 9.4)
Product Version 1.1.0 / 1.1.1-beta0071

**Additional context**

**Comment by matt-tolliday-iss** [comment]
Thanks @mattbrailsford - can I check if that's 1.2.0-rc0005? 

That version also seems to have lost the KonstruktRepository and IKonstruktRepositoryFactory references - is there a breaking change in 1.2.0 around repository usage not yet in docs?

**Comment by mattbrailsford** [comment]
@matt-tolliday-iss sorry no it should be 1.1.1-beta0025, 1.2.0 is the build I've been working on for Umbraco v10. You're welcome to use that one, but you'd need to Upgrade your Umbraco project to v10-RC4

**Comment by matt-tolliday-iss** [comment]
Thanks @mattbrailsford - I think ill hold off on that for a bit!

And sorry, just so I'm not doing this incorrectly - I was previously on 1.1.1-beta0071, but 1.1.1-beta0025 is the latest?

**Comment by mattbrailsford** [comment]
Hmm, that is weird. I’ll need to take a look and see why it’s done that 🤔

25 is the build that just occurred but why it’s built 25 when there are already older versions I’m not sure.

**Comment by mattbrailsford** [comment]
So, I use GitVersion to manage my version numbers and I think maybe because I started the 1.2.0 release branch it's reset it's build numbers for the 1.1.1 branch. You can install beta00025 and it will include everything that was in beta00071 I'm just not entirely sure how to force GitVersion to reliaze it's got it wrong 🤔

**Comment by matt-tolliday-iss** [comment]
Yeah it's a great tool - but frustrating to get exactly right sometimes. Quite a few options to juggle within the config I've always found. Thanks for confirming the build - I'll grab it shortly 👍

**Comment by mattbrailsford** [comment]
v1.1.1 has now been released
