### ISSUE TITLE
SetDeletedProperty hides all entities

### ISSUE THREAD

**Issue by matt-tolliday-iss** [outfielddigital/konstrukt#28]
**Describe the bug**
I'm trying to use `.SetDeletedProperty(p => p.IsDeleted) `on a collection, but it is neither showing records that have a True or False (1, 0) in the grid.

**Steps To Reproduce**
1. .SetDeletedProperty(p => p.IsDeleted)
2. View collection
3. No results shown

**Expected behavior**
Showing all records with a "True" or "1" value in the list view

**Screenshots**
![image](https://user-images.githubusercontent.com/80101704/170731480-e8ccc5da-e725-4a29-8454-37f948a181b4.png)

![image](https://user-images.githubusercontent.com/80101704/170731528-168feb38-5a05-4ac8-9e21-3e26e41bbacb.png)

**Environment (please complete the following information):**
Server OS: Win10
Browser Chrome
Umbraco Version 9.5.0 (Also 9.4)
Product Version 1.1.0 / 1.1.1-beta0025

**Comment by mattbrailsford** [comment]
Hey @matt-tolliday-iss this should now have been resolved in 1.1.1-beta00026 on the unstable feed 👍
