### ISSUE TITLE
EncryptedProperty - An error occurred during a cryptographic operation

### ISSUE THREAD

**Issue by matt-tolliday-iss** [outfielddigital/konstrukt#29]
**Describe the bug**

On create when encrypted property is enabled:
```
This exception was originally thrown at this call stack:
    Konstrukt.Web.Models.Mappers.KonstruktEditorMapper.ToEditModel(Konstrukt.Configuration.IFieldsetsConfig, string, object, bool, System.Collections.Generic.IEnumerable<Konstrukt.Configuration.KonstruktPropertyConfig>)
    Konstrukt.Web.Models.Mappers.KonstruktEntityMapper.ToEditModel(Konstrukt.Configuration.IKonstruktCollectionSourceConfig, Konstrukt.Configuration.KonstruktCollectionConfig, object)
    Konstrukt.Web.Controllers.Api.KonstruktApiController.GetEntityScaffold(string)
    Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(Microsoft.AspNetCore.Mvc.Infrastructure.IActionResultTypeMapper, Microsoft.Extensions.Internal.ObjectMethodExecutor, object, object[]) in ActionMethodExecutor.cs
    Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync.__Logged|12_1(Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in ExceptionDispatchInfo.cs

```

On edit:

`umbraco-backoffice-js.js.ve9bf0a294753f0d315f2945b571183f59d92ae25:152 Possibly unhandled rejection: {"errorMsg":"Failed to get entity by id","data":{"ExceptionMessage":"An error occurred during a cryptographic operation.","ExceptionType":null,"StackTrace":null},"status":500}`

**Steps To Reproduce**
1. configure an encrypted property .AddEncryptedProperty(p => p.SecureValue)
2. Click on edit/create
3. record fails to load, or error is thrown

**Expected behavior**
normal operation of create/edit functionality - unsure how encrypted property is intended to show

**Environment (please complete the following information):**
 - Server OS: Windows
 - BrowserChrome
 - Umbraco Version 9.5.0
 - Product Version 1.1.1-beta0026

**Comment by mattbrailsford** [comment]
Looks like the encryption methods don't handle null values so I've added some extra null checking before encrypting/decrypting. Should be on a new 1.1.1 beta build shortly.
