### ISSUE TITLE
Event Deleted and Deleting notifications cannot obtain the Entity

### ISSUE THREAD

**Issue by matt-tolliday-iss** [outfielddigital/konstrukt#30]
**Describe the bug**
When using the events `KonstruktEntityDeletingNotification `or `KonstruktEntityDeletedNotification` the .Entity property is of type "object" and so you cannot, as per the docs, obtain details of the Entity - it looks like it is actually a OperationResult<T> under the hood. But you cannot cast to that as it requires a value type, i believe.

```
public class SubscriberDeletedEventHandler : INotificationHandler<KonstruktEntityDeletingNotification>
    {
        private readonly IMemberService _memberService;

        public void Handle(KonstruktEntityDeletingNotification notification)
        {
            var subscriber = notification.Entity.**After** as SubscriberDto;
```

**Expected behavior**
(https://docs.getkonstrukt.net/advanced/events#konstruktentitydeletednotification)

**Environment (please complete the following information):**
 - Umbraco Version 9.5.0
 - Product Version 1.1.1

**Comment by mattbrailsford** [comment]
Good spot. These should indeed be the entity, not the OperationResult so it needs unwrapping.
