### ISSUE TITLE
Upgrade to Konstrukt 1.2+ & Umbraco 10

### ISSUE THREAD

**Issue by matt-tolliday-iss** [outfielddigital/konstrukt#31]
**Describe the bug**
On running through the update steps and upgrading of Umbraco/DB to .net 6 and 10, the site (from a front-end point of view, and the core backend works fine) but the Konstrukt section will not load.

On the very first load post-upgrade it did load, but did not load any of the data (all collections were empty). Also, when trying to create an entity it said the 'factory connection string was not configured correctly'

Have reset the value of RuntimeMinification::Version to a different value.

Any ideas on this one?

```
umbraco-backoffice-js.js.vc9657c693fd9b486511f4be8ea4f4a1d6ea9d8ef:147 Error: [$compile:multidir] http://errors.angularjs.org/1.8.3/$compile/multidir?p0=konstruktCollectionListView&p1=%20(module%3A%20umbraco.directives)&p2=konstruktCollectionListView&p3=%20(module%3A%20umbraco.directives)&p4=template&p5=%3Cdiv%20collection-alias%3D%22collectionAlias%22%20on-collection-loaded%3D%22onCollectionLoaded(collection)%22%20open-in-infinite-editor%3D%22false%22%3E
    at umbraco-backoffice-js.js.vc9657c693fd9b486511f4be8ea4f4a1d6ea9d8ef:25:168
    at ba (umbraco-backoffice-js.js.vc9657c693fd9b486511f4be8ea4f4a1d6ea9d8ef:103:448)
    at aa (umbraco-backoffice-js.js.vc9657c693fd9b486511f4be8ea4f4a1d6ea9d8ef:96:378)
    at umbraco-backoffice-js.js.vc9657c693fd9b486511f4be8ea4f4a1d6ea9d8ef:102:238
    at umbraco-backoffice-js.js.vc9657c693fd9b486511f4be8ea4f4a1d6ea9d8ef:159:454
    at m.$digest (umbraco-backoffice-js.js.vc9657c693fd9b486511f4be8ea4f4a1d6ea9d8ef:171:67)
    at m.$apply (umbraco-backoffice-js.js.vc9657c693fd9b486511f4be8ea4f4a1d6ea9d8ef:174:484)
    at HTMLAnchorElement.<anonymous> (umbraco-backoffice-js.js.vc9657c693fd9b486511f4be8ea4f4a1d6ea9d8ef:218:276)
    at HTMLAnchorElement.dispatch (umbraco-backoffice-js.js.vc9657c693fd9b486511f4be8ea4f4a1d6ea9d8ef:2:43064)
    at v.handle (umbraco-backoffice-js.js.vc9657c693fd9b486511f4be8ea4f4a1d6ea9d8ef:2:41048)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/80101704/176661332-964001aa-4fbe-48be-9def-4149ee14fb17.png)

**Environment (please complete the following information):**
 - Server OS: [e.g. iOS]
 - Umbraco Version 10.0.1
 - Product Version1.2.1-beta15

**Additional context**

**Comment by mattbrailsford** [comment]
Hey @matt-tolliday-iss first thing I'd say to check is that the new Konstrukt uses embedded UI files so should delete the `App_Plugins/Konstrukt` folder as it's now loaded from within the dlls. It may be a conflict with this that is complaining so try deleting that folder and see if it resolves it.

**Comment by matt-tolliday-iss** [comment]
That's solved all the front-end conflicts, thanks @mattbrailsford 

There is now still no data populating, and when trying to save a new entity I'm getting the message:

'Failed to save: The factory has not been configured with a proper connection string.'

**Comment by mattbrailsford** [comment]
Do you have anything with a stack trace in the trace log viewer?

**Comment by matt-tolliday-iss** [comment]
Nothing obvious on start-up - this is logged when attempting to save:

![image](https://user-images.githubusercontent.com/80101704/176678210-04f24231-9b66-456d-bbb0-c319abd6e7f0.png)

**Comment by matt-tolliday-iss** [comment]
https://our.umbraco.com/forum/using-umbraco-and-getting-started/99887-re-creating-an-umbraco-sites-database-with-custom-migrations

The only Google hit is this from 2019 - regarding composers?

**Comment by mattbrailsford** [comment]
Is your collection configured with a custom connection string? If so, what it is setup like in your app settings?

Basically it appears to be having problems resolving the connection string.

**Comment by matt-tolliday-iss** [comment]
No, the out-of-the-box original one:

![image](https://user-images.githubusercontent.com/80101704/176680396-1ae575b8-fea6-4a3d-af5e-122d3b7dfaf5.png)


I've seen this in the docs, but not using: [SetConnectionString](https://docs.getkonstrukt.net/collections/the-basics#changing-a-collection-connection-string)

**Comment by matt-tolliday-iss** [comment]
Setting it manually to: .`SetConnectionString("umbracoDbDSN")`

Same issue and message

**Comment by matt-tolliday-iss** [comment]
It does! Normal service resumes. That's a strange one. Many thanks @mattbrailsford

**Comment by mattbrailsford** [comment]
Ok cool, I'll add something in Konstrukt to make it fall back to the default provider in my code so I think that should fix it also.
