### ISSUE TITLE
Entity picker add button now showing correctly

### ISSUE THREAD

**Issue by mattbrailsford** [outfielddigital/konstrukt#39]
### Discussed in https://github.com/outfielddigital/konstrukt/discussions/38

<div type='discussions-op-text'>

<sup>Originally posted by **AaronSadlerUK** August 24, 2022</sup>
Feature request can the Entity Picker have an Edit button added, so that I don't need to Remove and Re-Add all entities when I want to add more 🙂</div>

It appears our ng-show statement is too strict on the add button and so it's being hidden when it shouldn't.

**Comment by mattbrailsford** [comment]
Big fix applied and available on our unstable feed (v1.5.2-beta0001) https://nuget.outfield.digital/unstable/v3/index.json

**Comment by AaronSadlerUK** [comment]
Same issue I'm afraid

![image](https://user-images.githubusercontent.com/9937803/186406735-992c6b3e-8c65-4d78-919d-ede220d8508b.png)

**Comment by mattbrailsford** [comment]
Have you cleared your browser cache? 🤔

**Comment by AaronSadlerUK** [comment]
I hate Edge sometimes 😅

We're all good 

![image](https://user-images.githubusercontent.com/9937803/186408019-4a7ecf75-7212-465a-b817-b823122ec02f.png)

**Comment by mattbrailsford** [comment]
Hehe, no worries. Glad it worked.

I've not long since done a release, so I'll give it a week or so before I push it out, but you should be pretty safe to stay on the beta for now. That's the only big fix in it since the previous release.

**Comment by mattbrailsford** [comment]
In 1.5.2 release
