### ISSUE TITLE
Save button not visible

### ISSUE THREAD

**Issue by matt-tolliday-iss** [outfielddigital/konstrukt#41]
**Describe the bug**
Since updating to 1.6.0 the "Save" button is no longer visible on any collection entity edit.

When creating a new entity the 'Save' button is also not visible.

The only option on all collections is now "Return to List"

Unsure if I have misread any of the release notes  has there been an update to enable the save button? Could it a permissions thing?

None of the collections have .DisableUpdate or .DisableCreate

Just noticed this in the DOM:

![image](https://user-images.githubusercontent.com/80101704/194325707-0d3e692a-417f-4b0f-b7d7-a22b40c44193.png)

**Steps To Reproduce**
1. Go to any collection
2. No Save button visible

**Expected behavior**
The Save button should be present and clickable.

**Screenshots**
![image](https://user-images.githubusercontent.com/80101704/194323702-fea9fcd5-c8e8-4595-a720-85978d4495db.png)

**Environment (please complete the following information):**
 - Server OS: [e.g. iOS]
 - Umbraco Version 10.2.1
 - Product Version 1.6.0

**Comment by matt-tolliday-iss** [comment]
I've refreashed my browser cache and no luck.

I can see this with package 1.6.0:

![image](https://user-images.githubusercontent.com/80101704/194341640-733506c6-2c5d-421f-a426-c5ca66053233.png)

looks as though there is no content rendered within it, are there any conditions around that? Or did I need to change any configuration to show it?

and this with package 1.5.2

![image](https://user-images.githubusercontent.com/80101704/194341936-5a827fc3-a78e-48f2-af6e-a60fe8ec9c40.png)

**Comment by mattbrailsford** [comment]
My gut feeling is that it's using the old JS for some reason as the buttons are defined in the edit controller. Given the markup is rendering, and the variables it binds to weren't present in the previous version it makes me think it's using the old file

**Comment by mattbrailsford** [comment]
🎉
