### ISSUE TITLE
'System.Data.SqlClient' wasn't found

### ISSUE THREAD

**Issue by chris-evansnz** [outfielddigital/konstrukt#42]
**Describe the bug**
Using Konstrukt in an Umbraco 10 website is working fine locally. But when we deployed the site to our staging server on Azure we get an error when trying to load the section in the backoffice.

```
The specified invariant name 'System.Data.SqlClient' wasn't found in the list of registered .NET Data Providers.

Exception Details
System.ApplicationException, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e: The specified invariant name 'System.Data.SqlClient' wasn't found in the list of registered .NET Data Providers.
```

**Steps To Reproduce**
Presumably it is environment-specific, but we deployed the site to a standard Azure App Service running on the S1 tier.

**Expected behavior**
We expected the custom section to load the same on our staging environment as it does on our local machines. We are not aware of any environment-specific configuration or settings we need to apply to ensure the SQL data connection can work?

**Screenshots**
![image](https://user-images.githubusercontent.com/58791033/194799566-dedd222a-8aa1-4997-b532-cda522cad265.png)

**Environment (please complete the following information):**
 - Server OS: Azure App Service
 - Browser : Chrome 106.0.5249.103 (Official Build) (64-bit)
 - Umbraco Version : 10.0.0
 - Product Version : 1.6.0

**Additional context**
Our implementation is using the free version of Konstrukt, with a single collection (which is just a simple SQL table with a few columns)

**Comment by mattbrailsford** [comment]
Hey @chris-evansnz 

Ahh, that old chestnut. We fixed a similar issue with Vendr recently.

I've pushed an update to our unstable feed at https://nuget.outfield.digital/unstable/v3/index.json if you want to test version 1.6.1-beta0001 and make sure it resolves the provlem for you that would be great.

**Comment by chris-evansnz** [comment]
Awesome thanks @mattbrailsford   -- that seems to have done the trick.

Let me know if/when this can get merged into a release version and we can upgrade our core branch to that.

Cheers!

**Comment by mattbrailsford** [comment]
Hey @chris-evansnz 

Cool, thanks for testing. I've pushed a 1.6.1 release out now which should resolve this issue.
