### ISSUE TITLE
Failed to get Entities - Enum filter without data view set

### ISSUE THREAD

**Issue by matt-tolliday-iss** [outfielddigital/konstrukt#45]
**Describe the bug**
When performing an Enum Filter on a Collection 500 ERROR is returned. Nothing is logged in the Log Viewer, but DEV console returns:

{"ExceptionMessage":"Sequence contains no elements","ExceptionType":null,"StackTrace":null}

The only difference to other collections where this does work is they have explcit defined Data Views, whereas the two collections that do not error.

<img width="387" alt="image" src="https://user-images.githubusercontent.com/80101704/212061510-79d70ff2-0a94-4439-b674-64d4b87f8475.png">

```
.AddFilterableProperty(p => p.Brand, filterconfig => filterconfig
      .SetLabel("Newsletter")
      .SetDescription("The magazine brand")
  )
```

```
[Column("Brand")]
public Brand Brand { get; set; }
```

**Steps To Reproduce**
1. Configure Collection with code as defined above
2. Click on funnel icon to filter and choose value
3. Click Apply

**Expected behavior**
The collection is filtered correctly.

**Environment (please complete the following information):**
 - Umbraco Version 10.3.2
 - Product Version 1.6.3-beta0008

**Comment by mattbrailsford** [comment]
Hmm, I've just tried to replicate this locally and it seems to be working for me 🤔

I'd assume this would fundamentally have to be a SQL error so are you able to see any errors logged in SSMS?

**Comment by matt-tolliday-iss** [comment]
Sorry @mattbrailsford - where do you mean logged in SSMS? [dbo].[umbracoLog]?

**Comment by mattbrailsford** [comment]
No, I just meant in whatever log SQL Server has (I may be miss remembering, but I thought you could see failed queries)

**Comment by matt-tolliday-iss** [comment]
Whereas with successful calls to FindEntities I see SQL dependency logs in our Application Insights - with the failed one there is no dependency logged, not even a failed one. Could it be code error before the calls are made?

On successful requests, I see a db dependency call to get a COUNT, and a call to get the data. 

No logs in SQL that appear useful, I'm afraid.

**Comment by mattbrailsford** [comment]
Hmm, then that's a bid weird. The code side of things should be working as that is defo working in my install so I'm not sure why that would be throwing an exception 🤔

**Comment by matt-tolliday-iss** [comment]
Just to prove the theory of the ticket, I've added a default view "All" with: 

`.AddDataView("All", p => p.Id != 0)`

And that now renders correctly, and filters the data correctly in the result set.

**Comment by mattbrailsford** [comment]
Ahh, ok, I've managed to replicate it now. I'll have to investigate how to resolve it as annoyingly it's coming from a complex bit 🤦‍♂️

**Comment by mattbrailsford** [comment]
Ok, I think I have something that works. I don't think it's the perfect solution, but it does the job. New unstable build should be available shortly.

**Comment by mattbrailsford** [comment]
PS no need to appologies. It's my bug to fix 😂

**Comment by mattbrailsford** [comment]
I actually think I've managed to implement the "best" fix for this now too so thought should be fixed the right way, plus a fallback fix 😁

**Comment by matt-tolliday-iss** [comment]
Working great, thanks @mattbrailsford 👍
