### ISSUE TITLE
Error upload file: The specified file type has been disallowed by the administrator

### ISSUE THREAD

**Issue by landlogicit** [outfielddigital/konstrukt#49]
**Describe the bug**
I have this error when i upload image file.

On Startup.cs i have this code :

.AddFieldset("Media", fieldsetConfig => fieldsetConfig
                                            .AddField(p => p.Avatar).SetDataType("Upload File")
                                        )

**Steps To Reproduce**
1. Go to 'Repositories'
2. Click on 'Person'
3. Select a person 
4. Upload image on Avatar property
5. Error show red: The specified file type has been disallowed by the administrator

**Environment (please complete the following information):**
 - Umbraco Version [e.g. 11.1.0]
 - Product Version [e.g. 1.6.3]

**Comment by mattbrailsford** [comment]
What's the file type of your image?

**Comment by landlogicit** [comment]
jpg

**Comment by mattbrailsford** [comment]
Hmm, that should be supported really. The allowed file types is really run by Umbraco as it's their property editor that is being reused so it should be using Umbraco's mechanisms for restricting file types, but I would have thought jpg should be fine

**Comment by mattbrailsford** [comment]
Have you configured the file uploads data types "Accepted file extensions"?

![image](https://user-images.githubusercontent.com/527305/213666137-e28bb726-c605-4c62-87d2-651f19ff04ac.png)

**Comment by mattbrailsford** [comment]
What is the exact extension of your file (you have extensions turned off in your video so I can't tell) and what is the exact config of your file upload field.

**Comment by landlogicit** [comment]
My config on startup.cs:
public void ConfigureServices(IServiceCollection services)
        {
            services.AddUmbraco(_env, _config)
                .AddBackOffice()
                .AddWebsite()
                .AddKonstrukt(cfg => {
                    cfg.AddSectionAfter("media", "Repositories", sectionConfig => sectionConfig
                        .Tree(treeConfig => treeConfig
                            .AddCollection<Persona>(x => x.Id, "Persona", "Persone", "A person entity", "icon-umb-users", "icon-umb-users",
                                collectionConfig => collectionConfig
                                .SetRepositoryType<PersonRepository>()
                                .SetNameProperty(p => p.Nome)
                                .ListView(listViewConfig => listViewConfig
                                    .AddField(p => p.TitoloLavoro).SetHeading("Job Title")
                                    .AddField(p => p.Email)
                                )
                                .Editor(editorConfig => editorConfig
                                    .AddTab("General", tabConfig => tabConfig
                                        .AddFieldset("General", fieldsetConfig => fieldsetConfig
                                            .AddField(p => p.TitoloLavoro).MakeRequired()
                                            .AddField(p => p.Eta)
                                            .AddField(p => p.Email).SetValidationRegex("[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+.[a-zA-Z0-9-.]+")
                                            .AddField(p => p.Telefono).SetDescription("inc area code")
                                        )
                                        .AddFieldset("Media", fieldsetConfig => fieldsetConfig
                                            .AddField(p => p.Avatar).SetDataType("Upload File")
                                        )
                                    )
                                )
                                .AddSearchableProperty(x=>x.Nome)
                                .AddFilterableProperty(x=>x.Nome )
                            )
                        )
                    );

                })
                .AddComposers()
                .AddPersone()
                .Build();
        }

**Comment by mattbrailsford** [comment]
This isn’t what I meant. You are pointing to the file upload data type, but I want to see the data types config in the settings section in the back office

**Comment by landlogicit** [comment]
look
![Animation2](https://user-images.githubusercontent.com/22096435/213748937-4e8a8991-8851-4fbf-b503-a6f725c31206.gif)

**Comment by mattbrailsford** [comment]
So yea, that’s likely your problem. You are supposed to configure that, adding the file extensions you want to allow. Because your list is empty, it’s probably refusing everything.

**Comment by landlogicit** [comment]
If I upload an image to a page I don't get any errors. The image is saved
![Animation3](https://user-images.githubusercontent.com/22096435/213753041-a158998d-bbcf-46b4-b551-5ad57fd99aa7.gif)

**Comment by mattbrailsford** [comment]
Ok, I’ll have to take a closer look next week

**Comment by landlogicit** [comment]
ok. thank you.

**Comment by mattbrailsford** [comment]
Ok, I've managed to find the issue. I've uploaded a fix to our unstable nuget feed at https://nuget.outfield.digital/unstable/v3/index.json if you want to test the v1.6.4-beta0001 that is on there and confirm this fixes the issues for you, that would be great.

**Comment by landlogicit** [comment]
i test and show this error on save :
Failed to save Person: Exception has been thrown by the target of an invocation.

**Comment by landlogicit** [comment]
Good Job. I tested your release version 1.6.4 and now i ahve no errors after uplad. All saved.
Thanks you.
